default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>

development:
  <<: *default
  database: lcms_engine_development
test:
  <<: *default
  database: lcms_engine_test
